// Command genredact turns the upstream gitleaks TOML rules file into a
// Go source file of regex patterns for the redact package.
//
// This is a developer tool, not part of the shipped binary. Run it when
// you want to refresh the vendored rule set:
//
//	curl -sSL -o /tmp/gitleaks.toml \
//	    https://raw.githubusercontent.com/gitleaks/gitleaks/master/config/gitleaks.toml
//	go run ./scripts/genredact \
//	    -in /tmp/gitleaks.toml \
//	    -out internal/redact/gitleaks_rules.go \
//	    -sha "$(git ls-remote https://github.com/gitleaks/gitleaks HEAD | cut -f1)"
//
// The script parses the TOML by hand (no deps), filters out rules whose
// regex won't compile under RE2, and emits a Go slice literal with the
// rule id and pattern. The generator deliberately drops gitleaks' noisy
// "generic-api-key" and "generic-password" rules — they have a false
// positive rate that's fine for a `gitleaks detect` report but not for
// rewriting message content in place.
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"regexp"
	"sort"
	"strings"
	"time"
)

type rule struct {
	id    string
	regex string
}

// Rules we intentionally skip — too noisy for in-place redaction.
var skip = map[string]bool{
	"generic-api-key":  true,
	"generic-password": true,
	// Curl -u user:pass is matched by a broader gitleaks rule that's
	// prone to eating legitimate text. We already have a narrower one in
	// the hand-rolled layer.
	"curl-auth-header":   true,
	"curl-auth-user":     true,
	"authenticated-url":  true,
	"jwt-base64":         true,
	"private-key":        true,
	"jwt":                true,
}

func main() {
	in := flag.String("in", "", "path to gitleaks.toml")
	out := flag.String("out", "", "path to emitted Go file")
	sha := flag.String("sha", "", "upstream commit sha for the header comment")
	pkg := flag.String("pkg", "redact", "generated package name")
	flag.Parse()
	if *in == "" || *out == "" {
		log.Fatal("both -in and -out are required")
	}

	f, err := os.Open(*in)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	rules, err := parse(f)
	if err != nil {
		log.Fatal(err)
	}

	kept := rules[:0]
	skipped := 0
	for _, r := range rules {
		if skip[r.id] {
			skipped++
			continue
		}
		if _, err := regexp.Compile(r.regex); err != nil {
			skipped++
			log.Printf("skip %s: regex doesn't compile under RE2: %v", r.id, err)
			continue
		}
		kept = append(kept, r)
	}
	sort.Slice(kept, func(i, j int) bool { return kept[i].id < kept[j].id })

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "// Code generated by scripts/genredact; DO NOT EDIT.")
	fmt.Fprintln(&buf, "//")
	fmt.Fprintln(&buf, "// Source: https://github.com/gitleaks/gitleaks")
	fmt.Fprintln(&buf, "// File:   config/gitleaks.toml")
	if *sha != "" {
		fmt.Fprintf(&buf, "// Commit: %s\n", *sha)
	}
	fmt.Fprintf(&buf, "// Refreshed: %s\n", time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintln(&buf, "//")
	fmt.Fprintln(&buf, "// Gitleaks rules are MIT-licensed. To refresh this file:")
	fmt.Fprintln(&buf, "//   curl -sSL -o /tmp/gitleaks.toml https://raw.githubusercontent.com/gitleaks/gitleaks/master/config/gitleaks.toml")
	fmt.Fprintln(&buf, "//   SHA=$(git ls-remote https://github.com/gitleaks/gitleaks HEAD | cut -f1)")
	fmt.Fprintln(&buf, "//   go run ./scripts/genredact -in /tmp/gitleaks.toml -out internal/redact/gitleaks_rules.go -sha $SHA")
	fmt.Fprintln(&buf)
	fmt.Fprintf(&buf, "package %s\n\n", *pkg)
	fmt.Fprintln(&buf, "// gitleaksRules is the vendored rule set — (id, regex) pairs only.")
	fmt.Fprintln(&buf, "// Metadata (entropy thresholds, allowlists, keywords) is intentionally")
	fmt.Fprintln(&buf, "// dropped; aii treats every match as a redaction candidate.")
	fmt.Fprintln(&buf, "var gitleaksRules = []namedPattern{")
	for _, r := range kept {
		fmt.Fprintf(&buf, "\t{id: %q, raw: %s},\n", r.id, goRawString(r.regex))
	}
	fmt.Fprintln(&buf, "}")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("gofmt: %v\n---\n%s", err, buf.String())
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatal(err)
	}
	log.Printf("wrote %d rules to %s (skipped %d)", len(kept), *out, skipped)
}

// parse reads just enough of the TOML to pull out [[rules]] id + regex.
// We avoid a TOML dependency by walking the file line by line; the
// gitleaks config is machine-generated and regular enough to allow this.
func parse(f *os.File) ([]rule, error) {
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 1<<20)

	var out []rule
	var cur *rule
	for sc.Scan() {
		line := sc.Text()
		trim := strings.TrimSpace(line)
		switch {
		case trim == "[[rules]]":
			if cur != nil && cur.id != "" && cur.regex != "" {
				out = append(out, *cur)
			}
			cur = &rule{}
		case strings.HasPrefix(trim, "[[rules.allowlists]]"),
			strings.HasPrefix(trim, "[rules.allowlist"):
			// Allowlist block — stop populating the current rule's
			// regex, but keep its id so we still emit it if we already
			// captured a regex.
			if cur != nil && cur.id != "" && cur.regex != "" {
				out = append(out, *cur)
			}
			cur = nil
		case cur != nil && strings.HasPrefix(trim, "id = "):
			cur.id = unquote(trim[len("id = "):])
		case cur != nil && strings.HasPrefix(trim, "regex = "):
			cur.regex = unquote(trim[len("regex = "):])
		}
	}
	if cur != nil && cur.id != "" && cur.regex != "" {
		out = append(out, *cur)
	}
	return out, sc.Err()
}

// unquote strips TOML triple-single-quote or double-quote delimiters and
// undoes the common escape sequences. TOML literal strings ('''…''' /
// '…') are the only form the gitleaks config uses for regex values, so
// we don't need a full unescape.
func unquote(s string) string {
	s = strings.TrimSpace(s)
	switch {
	case strings.HasPrefix(s, "'''") && strings.HasSuffix(s, "'''"):
		return s[3 : len(s)-3]
	case strings.HasPrefix(s, `"""`) && strings.HasSuffix(s, `"""`):
		return s[3 : len(s)-3]
	case strings.HasPrefix(s, "'") && strings.HasSuffix(s, "'"):
		return s[1 : len(s)-1]
	case strings.HasPrefix(s, `"`) && strings.HasSuffix(s, `"`):
		return s[1 : len(s)-1]
	}
	return s
}

// goRawString emits a Go raw-string literal for s if possible, falling
// back to an interpreted literal when s contains a backtick. Regex
// literals are full of backslashes, so raw strings are much cleaner.
func goRawString(s string) string {
	if !strings.ContainsRune(s, '`') {
		return "`" + s + "`"
	}
	return fmt.Sprintf("%q", s)
}
